### ISSUE TITLE
how to make the API RedisReplyPtr redisCommand(const char *format, ...); thread safe? 

### ISSUE THREAD

**Issue by savagecm** [aclisp/hiredispool#1]
As I know, hiredis is not thread-safe, I saw the following code:

`

    // redisCommand is a thread-safe wrapper of that function in hiredis
    // It first get a connection from pool, execute the command on that
    // connection and then release the connection to pool.
    // the command's reply is returned as a smart pointer,
    // which can be used just like raw redisReply pointer.
    RedisReplyPtr redisCommand(const char *format, ...);
    RedisReplyPtr redisvCommand(const char *format, va_list ap);
    RedisReplyPtr redisCommandArgv(int argc, const char **argv, const size_t *argvlen);    

`
the command may run in different thread(not in hiredis, poll thread), what did you do to make it thread-safe?
The i-buffer in hiredis not thread-safe. 
when we call redisCommand of hiredis. it write the command to the i-buffer.

For example we call the API in thread A, and the polling thread is thread B.
we may call the API you marked thread-safe:
`
RedisReplyPtr redisCommand(const char *format, ...);
`
we write command to the i-buffer in thread A, but the i-buffer is read in thread B, how to make it thread safe?

**Comment by aclisp** [comment]
hi Max, I do not understand what do you mean by `i-buffer` exactly. But this `i-buffer` should be attached to one connection (which is a redisContext pointer returned by redisConnect). If you dig into the implement of  `RedisReplyPtr redisCommand(const char *format, ...);`, it will peak up one connection from the pool every time you call it. That means in you get different redisConext from different thread.

**Comment by savagecm** [comment]
Hi aclisp,
you can find the following words in the README of hiredis(https://github.com/redis/hiredis) :

> Note: A redisAsyncContext is not thread-safe.

**Comment by savagecm** [comment]
Yes we can get different context, but the context is not thread-safe, you can only use it in the "loop"(maybe ae, libevent, libuv or else....) thread.

**Comment by savagecm** [comment]
add more, you can also find the words: 

> Note: A redisContext is not thread-safe.
which means both redisContext  and redisAsyncContext  is not thread-safe

**Comment by savagecm** [comment]
the context is not thread-safe, how can this API thread-safe?

**Comment by aclisp** [comment]
This API guarantees the redisContext will never be shared across thread.

**Comment by savagecm** [comment]
I just realized that this API support only SYNC mode....
What I asked is about async mode. Sorry for that
