### ISSUE TITLE
 cc1: error: unrecognized command line option "-Wpedantic"

### ISSUE THREAD

**Issue by yaqiangxue** [aclisp/hiredispool#2]
gcc -std=c99 -c -O0 -pthread -fPIC  -Wall -Wpedantic -W -Wstrict-prototypes -Wwrite-strings -g -ggdb  -D_GNU_SOURCE log.c
cc1: error: unrecognized command line option "-Wpedantic"
make: *** [log.o] Error 1

could you please tell me how to solve this problem？

**Comment by aclisp** [comment]
Either upgrade your gcc or remove '-Wpedantic' option from Makefile. You can refer to https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

**Comment by yaqiangxue** [comment]
谢谢。
