### ISSUE TITLE
Pool and Unix sockets?

### ISSUE THREAD

**Issue by sdmrnv** [aclisp/hiredispool#8]
Hello!

When I try to use Unix socket with this module replacing redisConnectWithTimeout by redisConnectUnixWithTimeout in hiredispool.c I get error: "WARN  connect_single_socket: Failed to enable keepalive: Operation not supported"

So does any methods exist to use unix socket with hiredispool?

**Comment by aclisp** [comment]
This WARN message can be ignored. You got it because unix socket does not support keepalive.
