### ISSUE TITLE
Multi threads clients cause error

### ISSUE THREAD

**Issue by thebirdfromsea** [aclisp/hiredispool#9]
I use a multi threads client to send request to Redis. It works fine when my total thread number is 16. After I change it to 32, it give me error below: 

2021/06/08 13:57:22 WARN  redis_get_socket: There are no redis handles to use! skipped 0, tried to connect 0
2021/06/08 13:57:22 ERROR Can not get socket from redis connection pool, server down? or not enough connection?

What could be the reason?

**Comment by aclisp** [comment]
Try to increase the `num_redis_socks` in `REDIS_CONFIG` when you init your pool with `redis_pool_create`.

**Comment by thebirdfromsea** [comment]
Thank you. I will try. Does this library support pipeline?

**Comment by aclisp** [comment]
It does not support pipeline.

**Comment by thebirdfromsea** [comment]
Okay. Does it support MSET and MGET?
